import React, { Fragment } from 'react';
import { Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    invoiceNoContainer: {
        flexDirection: 'row',
        marginTop: 36,
        justifyContent: 'flex-end'
    },
    invoiceDateContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end'
    },
    invoiceDate: {
        fontSize: 12,
        fontStyle: 'bold',
    },
    label: {
        width: 120,
        textAlign: 'right',
        paddingLeft:5,
    }
});
let today = new Date()
let date = today.getDate() + '-' + parseInt(today.getMonth() + 1) + '-' + today.getFullYear()

const InvoiceNo = ({ invoice }) => (
    <Fragment>       
        <View style={styles.invoiceDateContainer}>
            <Text style={styles.label}>Date: </Text>
            <Text  style={styles.invoiceDate}>{date}</Text>
        </View>
        <View style={styles.invoiceDateContainer}>
            <Text style={styles.label}>Generated By: </Text>
            <Text style={styles.invoiceDate}>BTFS</Text>
        </View >
    </Fragment>
);

export default InvoiceNo;